Repository pbg0205/issue-tracker, pull requests merged in 2021-07, with the labels that each got.

#101 [FE] API 수정 및 레이블/마일스톤 페이지간 공유하는 버튼 토글 버그 수정
  frontend/src/components/Labels/Labels.jsx
  frontend/src/components/Milestones/MilestoneInput.jsx
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/components/Milestones/MilestonesHeader.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/util/API.js
Labels: FE, fix

#103 [FE] Filter Modal 오류 해결
  frontend/build.zip
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/common/Button/DropDownButton.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/common/IssueCategory/IssueCategory.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryList.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/data.js
  frontend/src/util/API.js
  frontend/src/util/getEngKey.js
Labels: FE

#105 [FE] issue detail page
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/components/common/IssueCategory/Label.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
Labels: FE, feat

#107 [FE] 이슈 관련 기능 추가
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/IssueDetail/IssueDetailHeader.jsx
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/data.js
  frontend/src/util/getEngKey.js
Labels: FE, feat

#108 [FE] 선택된 이슈들 열기/닫기 + 이슈 코멘트 수정 기능 추가
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/FilterModal.jsx
Labels: FE, feat

#109 Fe/feat/issue detail 구현 완료
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/util/API.js
Labels: FE, feat

#110 [FE] fix: 코멘트 수정시 기존 내용 렌더링, 코멘트 편집 취소 기능 추가
  frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx
  frontend/src/components/common/CommentInput.jsx
Labels: FE, feat, fix

#114 [FE] 새 코멘트 등록시 not function 에러 뜨는 것 해결
  frontend/src/components/common/CommentInput.jsx
Labels: FE, fix

#115 feat: 이슈 카테고리 milestone progress bar 추가(#112)
  frontend/src/components/common/IssueCategory/Milestone.jsx
Labels: FE, feat

#116 [FE] 버그 해결, 스타일 수정
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/components/common/IssueCategory/Milestone.jsx
Labels: FE, fix

#117 [FE] 초기 메인 페이지 진입시 열린 이슈만 렌더링
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Issues.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/components/pages/LoginLoadingPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/data.js
  frontend/src/hooks/useDebounce.jsx
  frontend/src/util/qsParser.js
Labels: FE, feat

#118 [FE] 필터모달 목데이터에서 fetched 데이터로 변경
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/data.js
Labels: FE, feat

#119 [FE] filter modal 값 선택에 따른 라우팅 처리 (진행중)
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/common/Button/BlueButtons.jsx
  frontend/src/components/common/Button/ButtonGroup.jsx
  frontend/src/components/common/Button/WhiteButtons.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/styles/StyledButtons.jsx
  frontend/src/util/getQueryString.js
Labels: FE, feat

#120 [FE] 필터 모달 라디오 선택 값이 쿼리스트링에 한박자 늦게 반영되는 버그 수정
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/components/pages/LoginLoadingPage.jsx
  frontend/src/components/pages/MainPage.jsx
Labels: FE, fix

#122 [FE] 코멘트 편집 누르면 새 코멘트 부분도 채워지는 버그 수정
  frontend/src/components/Issues/Menu/Menu.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/pages/MainPage.jsx
Labels: FE, fix

#124 [FE] Main page 레이블/마일스톤 갯수, 열린/닫힌 이슈, query string reset
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/Menu.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/Labels/Labels.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/util/fetchData.js
  frontend/src/util/getFilteredData.js
Labels: FE, feat

#125 [FE] 자잘한 버그 수정
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/components/Milestones/MilestonesHeader.jsx
  frontend/src/components/common/Button/DropDownButton.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/data.js
  frontend/src/util/getFilterList.js
Labels: FE, feat

#127 [FE] feat: PR 템플릿 추가
  frontend/.github/ISSUE_TEMPLATE.md
  frontend/.github/PULL_REQUEST_TEMPLATE.md
Labels: FE, feat

#131 [FE] 이슈 필터링
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Milestones/MilestonesHeader.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/data.js
  frontend/src/hooks/useFetch.jsx
  frontend/src/util/fetchData.js
  frontend/src/util/fetchImage.js
  frontend/src/util/getFilteredData.js
Labels: FE, feat
