Repository pbg0205/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#1 feat: CRA 추가
  frontend/.gitignore
  frontend/README.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/yarn.lock
Labels: FE

#7 [FE] Fe/feat/routing
  frontend/package.json
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.jsx
  frontend/src/components/Issues/Issues.jsx
  frontend/src/components/Labels/Labels.jsx
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/components/pages/LoginLoadingPage.jsx
  frontend/src/components/pages/LoginPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/index.js
  frontend/src/index.jsx
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/yarn.lock
Labels: FE

#15 [FE] Fe/feat/routing
  frontend/src/App.jsx
  frontend/src/components/common/PrivateRoute.jsx
  frontend/src/components/pages/LoginLoadingPage.jsx
  frontend/src/components/pages/LoginPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/util/API.js
Labels: FE

#17 [FE] main page routing 완성
  frontend/src/App.jsx
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Header/Menu.jsx
  frontend/src/components/Header/Navigator.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/pages/NewIssue.jsx
  frontend/src/components/pages/NoMatch.jsx
Labels: FE, feat

#18 [Be] github login 기능 구현
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/com/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/com/codesquad/issuetracker/user/component/GitHubOauthIosValues.java
  BE/src/main/java/com/codesquad/issuetracker/user/component/GitHubOauthValues.java
  BE/src/main/java/com/codesquad/issuetracker/user/component/GitHubOauthWebValues.java
  BE/src/main/java/com/codesquad/issuetracker/user/component/JwtUtils.java
  BE/src/main/java/com/codesquad/issuetracker/user/controller/AuthController.java
  BE/src/main/java/com/codesquad/issuetracker/user/dto/AccessTokenRequest.java
  BE/src/main/java/com/codesquad/issuetracker/user/dto/AccessTokenResponse.java
  BE/src/main/java/com/codesquad/issuetracker/user/dto/GithubUser.java
  BE/src/main/java/com/codesquad/issuetracker/user/dto/JwtResponse.java
  BE/src/main/java/com/codesquad/issuetracker/user/service/GithubLoginService.java
  BE/src/main/resources/application.properties
Labels: BE, feat

#21 [FE] feat: 페이지 컴포넌트별 빈 jsx파일 생성 (#20)
  frontend/src/App.jsx
  frontend/src/components/IssueDetail/IssueDatailHeader.jsx
  frontend/src/components/IssueDetail/IssueDetail.jsx
  frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx
  frontend/src/components/IssueDetail/IssueDetailComments.jsx
  frontend/src/components/Issues/Header.jsx
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/Menu.jsx
  frontend/src/components/Issues/Menu/MenuFilter.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/Labels/LabelCard.jsx
  frontend/src/components/Labels/LabelInput.jsx
  frontend/src/components/Milestones/MilestoneCard.jsx
  frontend/src/components/Milestones/MilestoneInput.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/NewIssues/NewIssueInput.jsx
  frontend/src/components/NewIssues/NewIssues.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/common/IssueCategoryInput.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/components/pages/LabelsPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/pages/MilestonesPage.jsx
  frontend/src/components/pages/NewIssuePage.jsx
  frontend/src/components/pages/NoMatchPage.jsx
Labels: FE, feat

#28 [FE] Fe/feat/login page view
  frontend/jsconfig.json
  frontend/src/components/pages/LoginLoadingPage.jsx
  frontend/src/components/pages/LoginPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/util/API.js
  frontend/src/images/LogotypeLarge.svg
  frontend/src/images/LogotypeMedium.svg
  frontend/src/images/Property 1=UserImageLarge.svg
  frontend/src/images/Property 1=UserImageSmall.svg
  frontend/src/images/Property 1=alert-circle.svg
  frontend/src/images/Property 1=archive.svg
  frontend/src/images/Property 1=calendar.svg
  frontend/src/images/Property 1=checc box initial.svg
  frontend/src/images/Property 1=check box active.svg
  frontend/src/images/Property 1=check box disable.svg
  frontend/src/images/Property 1=check-off-circle.svg
  frontend/src/images/Property 1=check-on-circle.svg
  frontend/src/images/Property 1=edit.svg
  frontend/src/images/Property 1=milestone.svg
  frontend/src/images/Property 1=paperclip.svg
  frontend/src/images/Property 1=plus.svg
  frontend/src/images/Property 1=refresh-ccw.svg
  frontend/src/images/Property 1=search.svg
  frontend/src/images/Property 1=smile.svg
  frontend/src/images/Property 1=tag.svg
  frontend/src/images/Property 1=trash.svg
  frontend/src/images/Property 1=x-square.svg
  frontend/src/styles/GlobalStyle.jsx
  frontend/src/styles/Responsive.jsx
  frontend/src/styles/StyledButtons.jsx
  frontend/src/styles/theme.js
  frontend/src/util/API.js
Labels: FE

#34 [FE] WIP: issue-list 작업중
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Issues.jsx
  frontend/src/images/chevron_down.svg
  frontend/src/styles/GlobalStyle.jsx
Labels: FE

#35 [FE] Fe/feat/menu filter bar
  frontend/src/App.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/Issues.jsx
  frontend/src/components/Issues/Menu/Menu.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/styles/StyledButtons.jsx
Labels: FE

#37 [FE] chore: 로그인 버튼 Material-UI 적용
  frontend/src/components/pages/LoginPage.jsx
  frontend/src/styles/StyledButtons.jsx
Labels: FE

#39 [FE] Fe/feat/issue list 작업중
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/pages/NoMatch.jsx
  frontend/src/data.js
  frontend/src/util/getTimeStamp.js
Labels: FE

#40 [FE] Menu Filter bar, Issue List merge
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/common/AddButton.jsx
  frontend/src/components/common/ButtonGroup.jsx
  frontend/src/components/common/DropDownButton.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/images/arrow_down.svg
  frontend/src/images/milestone.svg
  frontend/src/images/plus.svg
  frontend/src/images/search.svg
  frontend/src/images/tag.svg
  frontend/src/styles/StyledButtons.jsx
  frontend/src/styles/theme.js
Labels: FE, feat

#33 [BE] Label CRUD
  BE/src/main/java/com/codesquad/issuetracker/label/controller/LabelController.java
  BE/src/main/java/com/codesquad/issuetracker/label/domain/Colors.java
  BE/src/main/java/com/codesquad/issuetracker/label/domain/Label.java
  BE/src/main/java/com/codesquad/issuetracker/label/dto/ColorsDto.java
  BE/src/main/java/com/codesquad/issuetracker/label/dto/LabelDto.java
  BE/src/main/java/com/codesquad/issuetracker/label/dto/LabelRequestDto.java
  BE/src/main/java/com/codesquad/issuetracker/label/dto/LabelWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/label/dto/LabelsWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/label/repository/LabelRepository.java
  BE/src/main/java/com/codesquad/issuetracker/label/service/LabelService.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/codesquad/issuetracker/label/domain/ColorsTest.java
  BE/src/test/java/com/codesquad/issuetracker/label/domain/LabelTest.java
  BE/src/test/java/com/codesquad/issuetracker/label/repository/LabelRepositoryTest.java
Labels: BE, feat

#38 [BE] Milestone CRUD
  BE/src/main/java/com/codesquad/issuetracker/milestone/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneRequestDto.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponseDto.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestonesWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/infra/MilestoneRepository.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/service/MilestoneService.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/codesquad/issuetracker/milestone/domain/MilestoneTest.java
Labels: BE, feat

#44 [FE] 1주차 PR 이후 이어서 진행
  frontend/src/App.jsx
  frontend/src/MyRecoil/atom.js
  frontend/src/MyRecoil/store.js
  frontend/src/MyRecoil/useRecoilState.js
  frontend/src/MyRecoil/useRecoilValue.js
  frontend/src/MyRecoil/useSetRecoilState.js
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/pages/AnotherTest.jsx
  frontend/src/components/pages/LoginPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/pages/Test.jsx
  frontend/src/index.jsx
  frontend/src/styles/StyledButtons.jsx
  frontend/src/styles/theme.js
  frontend/src/util/getTimeStamp.js
Labels: FE

#46 [BE] comment 기능 구현
  BE/src/main/java/com/codesquad/issuetracker/comment/controller/CommentController.java
  BE/src/main/java/com/codesquad/issuetracker/comment/domain/Comment.java
  BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentRequest.java
  BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentResponse.java
  BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentsWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/comment/infra/CommentRepository.java
  BE/src/main/java/com/codesquad/issuetracker/comment/service/CommentService.java
Labels: BE, feat

#47 [FE] FilterModal 기능 구현
  frontend/src/MyRecoil/atom.js
  frontend/src/MyRecoil/index.js
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/common/ButtonGroup.jsx
  frontend/src/components/common/DropDownButton.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/data.js
  frontend/src/images/radio_button_checked.svg
  frontend/src/images/radio_button_default.svg
  frontend/src/styles/StyledButtons.jsx
  frontend/src/styles/theme.js
Labels: FE, feat

#48 [FE] 이슈리스트
  frontend/src/MyRecoil/atom.js
  frontend/src/MyRecoil/useRecoilState.js
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/data.js
  frontend/src/util/getTimeStamp.js
Labels: FE

#49 [FE] : fix: 체크박스 로직 수정
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/index.jsx
Labels: FE

#51 [FE] feat: 선택된 이슈 열기/닫기 모달 추가
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/data.js
Labels: FE

#53 [FE] filter bar 진행중
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/util/API.js
Labels: FE, feat

#54 [FE] Goody 의 page move 랑 Daisy issue-filter 머지
  frontend/src/App.jsx
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/common/ButtonGroup.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/components/pages/LabelsPage.jsx
  frontend/src/components/pages/LoginLoadingPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/pages/MilestonesPage.jsx
  frontend/src/components/pages/NewIssuePage.jsx
  frontend/src/util/getUserInfo.js
Labels: FE

#57 [FE] new issue 페이지 HTML 틀 잡기
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/NewIssues/NewIssueInput.jsx
  frontend/src/components/common/CancelButton.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/components/common/IssueCategoryList.jsx
  frontend/src/components/common/SubmitButton.jsx
  frontend/src/components/pages/NewIssuePage.jsx
  frontend/src/data.js
  frontend/src/styles/StyledButtons.jsx
  frontend/src/styles/theme.js
  frontend/src/util/getEngKey.js
  frontend/src/util/getUserInfo.js
Labels: FE

#59 [FE] 레이블 페이지와 마일스톤 페이지 HTML 구조화 적용
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/Labels/LabelCard.jsx
  frontend/src/components/Labels/Labels.jsx
  frontend/src/components/Labels/LabelsHeader.jsx
  frontend/src/components/Milestones/MilestoneCard.jsx
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/components/Milestones/MilestonesHeader.jsx
  frontend/src/components/common/ButtonGroup.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/components/pages/LabelsPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/pages/MilestonesPage.jsx
  frontend/src/styles/StyledCards.jsx
  frontend/src/util/getGridRateStyle.js
Labels: FE

#56 [FE] filterBar 완성중
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/common/ButtonGroup.jsx
  frontend/src/components/common/DropDownButton.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/styles/StyledButtons.jsx
Labels: FE, feat

#60 [BE] issue 기본 기능 구현
  BE/src/main/java/com/codesquad/issuetracker/auth/component/JwtUtils.java
  BE/src/main/java/com/codesquad/issuetracker/auth/interceptor/AuthInterceptor.java
  BE/src/main/java/com/codesquad/issuetracker/comment/controller/CommentController.java
  BE/src/main/java/com/codesquad/issuetracker/comment/domain/Comment.java
  BE/src/main/java/com/codesquad/issuetracker/comment/dto/CommentRequest.java
  BE/src/main/java/com/codesquad/issuetracker/comment/infra/CommentRepository.java
  BE/src/main/java/com/codesquad/issuetracker/comment/service/CommentService.java
  BE/src/main/java/com/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issuetracker/issue/domain/Issue.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/AssigneeIdRequest.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueRequest.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueResponse.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueSummaryResponse.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssuesWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/LabelIdRequest.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/MilestoneIdRequest.java
  BE/src/main/java/com/codesquad/issuetracker/issue/infra/IssueRepository.java
  BE/src/main/java/com/codesquad/issuetracker/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponseDto.java
  BE/src/main/java/com/codesquad/issuetracker/user/domain/User.java
  BE/src/main/java/com/codesquad/issuetracker/user/dto/UserDto.java
  BE/src/test/java/com/codesquad/issuetracker/issue/infra/IssueRepositoryTest.java
Labels: BE, feat

#62 [FE] 네비게이터 전역으로 다시 옮김
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/Milestones/MilestoneCard.jsx
  frontend/src/components/Milestones/MilestonesHeader.jsx
  frontend/src/components/pages/LabelsPage.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/pages/MilestonesPage.jsx
  frontend/src/styles/StyledCards.jsx
  frontend/src/styles/theme.js
Labels: FE

#64 [FE] feat: 레이블/마일스톤 페이지 탭버튼 배경효과
  frontend/src/MyRecoil/atom.js
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/common/ButtonGroup.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/components/pages/AnotherTest.jsx
  frontend/src/components/pages/MainPage.jsx
  frontend/src/components/pages/Test.jsx
  frontend/src/styles/StyledButtons.jsx
Labels: FE

#65 [BE] MySQL DB
  BE/build.gradle
  BE/src/main/java/com/codesquad/issuetracker/issue/domain/Issue.java
  BE/src/main/resources/application.properties
Labels: BE, refactor

#66 [FE] Label 페이지 Style 적용
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/Labels/LabelCard.jsx
  frontend/src/components/Labels/LabelInput.jsx
  frontend/src/components/Labels/Labels.jsx
  frontend/src/components/Labels/LabelsHeader.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/common/Button/AddButton.jsx
  frontend/src/components/common/Button/ButtonGroup.jsx
  frontend/src/components/common/Button/CancelButton.jsx
  frontend/src/components/common/Button/DropDownButton.jsx
  frontend/src/components/common/Button/SubmitButton.jsx
  frontend/src/components/common/FilterModal.jsx
  frontend/src/components/common/LabelBadge.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/data.js
  frontend/src/images/edit.svg
  frontend/src/images/trash.svg
  frontend/src/styles/StyledLayout .jsx
Labels: FE, feat

#67 [FE] Fe/feat/milestone
  frontend/src/components/Milestones/MilestoneCard.jsx
  frontend/src/components/Milestones/MilestoneInput.jsx
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/components/Milestones/MilestonesHeader.jsx
  frontend/src/components/common/CloseButton.jsx
  frontend/src/components/pages/MilestonesPage.jsx
  frontend/src/hooks/useFetchGet.jsx
  frontend/src/util/getPercent.js
Labels: FE

#68 [FE] feat: useFecth 커스텀 훅
  frontend/src/components/pages/MilestonesPage.jsx
  frontend/src/hooks/useFetchGet.jsx
Labels: FE

#70 [FE] Fe/feat/milestone
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Milestones/MilestoneCard.jsx
  frontend/src/components/Milestones/MilestoneInput.jsx
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/components/pages/MilestonesPage.jsx
  frontend/src/hooks/useFetch.jsx
  frontend/src/hooks/useFetchGet.jsx
  frontend/src/util/fetchData.js
Labels: FE

#69 [FE] Label Page view
  frontend/src/components/Labels/LabelCard.jsx
  frontend/src/components/Labels/LabelInput.jsx
  frontend/src/components/Labels/Labels.jsx
  frontend/src/components/common/LabelBadge.jsx
  frontend/src/data.js
  frontend/src/hooks/useDebounce.jsx
  frontend/src/hooks/useFetch.jsx
  frontend/src/images/x-square.svg
  frontend/src/styles/StyledLayout .jsx
  frontend/src/styles/theme.js
Labels: FE, feat

#71 [FE] Fe/feat/milestone
  frontend/src/components/Milestones/MilestoneCard.jsx
  frontend/src/components/Milestones/MilestoneInput.jsx
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/hooks/useFetch.jsx
Labels: FE

#73 [FE] Button 컴포넌트 추상화 및 적용
  frontend/src/components/Issues/Menu/MenuFilterBar.jsx
  frontend/src/components/Issues/Menu/MenuTab.jsx
  frontend/src/components/Labels/LabelInput.jsx
  frontend/src/components/Milestones/MilestoneInput.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/common/Button/AddButton.jsx
  frontend/src/components/common/Button/BlueButtons.jsx
  frontend/src/components/common/Button/CancelButton.jsx
  frontend/src/components/common/Button/DropDownButton.jsx
  frontend/src/components/common/Button/SubmitButton.jsx
  frontend/src/components/common/Button/WhiteButtons.jsx
  frontend/src/components/common/CloseButton.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/styles/StyledButtons.jsx
  frontend/src/styles/theme.js
Labels: FE, refactor

#74 [FE] feat: 마일스톤 put, post 완성
  frontend/src/components/Milestones/MilestoneCard.jsx
  frontend/src/components/Milestones/MilestoneInput.jsx
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/util/fetchData.js
Labels: FE

#76 [BE] review 반영
  BE/src/main/java/com/codesquad/issuetracker/auth/component/JwtUtils.java
  BE/src/main/java/com/codesquad/issuetracker/auth/interceptor/AuthInterceptor.java
  BE/src/main/java/com/codesquad/issuetracker/auth/service/GithubLoginService.java
  BE/src/main/java/com/codesquad/issuetracker/comment/controller/CommentController.java
  BE/src/main/java/com/codesquad/issuetracker/comment/service/CommentService.java
  BE/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issuetracker/issue/domain/Issue.java
  BE/src/main/java/com/codesquad/issuetracker/user/domain/User.java
  BE/src/main/java/com/codesquad/issuetracker/user/dto/UserDto.java
  BE/src/test/java/com/codesquad/issuetracker/milestone/domain/MilestoneTest.java
Labels: BE

#77 [FE] Fe/feat/milestone dev
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Milestones/MilestoneInput.jsx
  frontend/src/components/Milestones/Milestones.jsx
  frontend/src/components/common/Navigator.jsx
Labels: FE

#75 [FE] label page API 연동
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Labels/LabelCard.jsx
  frontend/src/components/Labels/LabelInput.jsx
  frontend/src/components/Labels/Labels.jsx
  frontend/src/components/common/Navigator.jsx
  frontend/src/data.js
  frontend/src/util/fetchData.js
Labels: FE, feat

#79 [BE] 이미지 업로드 기능
  BE/build.gradle
  BE/src/main/java/com/codesquad/issuetracker/config/AmazonS3Config.java
  BE/src/main/java/com/codesquad/issuetracker/image/component/S3Uploader.java
  BE/src/main/java/com/codesquad/issuetracker/image/controller/ImageUploadController.java
  BE/src/main/java/com/codesquad/issuetracker/image/dto/Image.java
  BE/src/main/java/com/codesquad/issuetracker/image/dto/ImageWrapper.java
  BE/src/main/java/com/codesquad/issuetracker/image/service/ImageUploadService.java
  BE/src/main/resources/application-aws.properties
  BE/src/main/resources/application.properties
Labels: BE, feat

#72 Github 로그인 기능 구현
  iOS/Podfile
  iOS/Podfile.lock
  iOS/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/Info.plist
  iOS/issue-tracker/IssueList/IssueCoordinator.swift
  iOS/issue-tracker/IssueList/IssueListViewController.swift
  iOS/issue-tracker/Login/JWT.swift
  iOS/issue-tracker/Login/LoginDelegates.swift
  iOS/issue-tracker/Login/LoginUseCase.swift
  iOS/issue-tracker/Login/LoginViewController.swift
  iOS/issue-tracker/Login/LoginViewModel.swift
  iOS/issue-tracker/Model/User.swift
  iOS/issue-tracker/Network/EndPoint.swift
  iOS/issue-tracker/Network/NetworkRequester.swift
  iOS/issue-tracker/Network/NetworkService.swift
  iOS/issue-tracker/Supporting/AppDelegate.swift
Labels: feat, iOS

#81 [BE] 예외처리 기능 구현
  BE/src/main/java/com/codesquad/issuetracker/auth/component/JwtUtils.java
  BE/src/main/java/com/codesquad/issuetracker/auth/interceptor/AuthInterceptor.java
  BE/src/main/java/com/codesquad/issuetracker/auth/service/GithubLoginService.java
  BE/src/main/java/com/codesquad/issuetracker/comment/service/CommentService.java
  BE/src/main/java/com/codesquad/issuetracker/exception/BadRequestException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/BadTokenRequestException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/CommentNotFoundException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/HttpException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/HttpExceptionHandler.java
  BE/src/main/java/com/codesquad/issuetracker/exception/IssueNotFoundException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/LabelNotFoundException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/MilestoneNotFoundException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/NotFoundException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/S3UploadFailException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/UnauthorizedException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/issuetracker/exception/dto/HttpExceptionResponse.java
  BE/src/main/java/com/codesquad/issuetracker/image/component/S3Uploader.java
  BE/src/main/java/com/codesquad/issuetracker/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issuetracker/label/service/LabelService.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/service/MilestoneService.java
Labels: BE, feat

#84 [FE] label page merge
  frontend/src/components/Labels/LabelCard.jsx
  frontend/src/components/Labels/LabelInput.jsx
  frontend/src/components/Labels/Labels.jsx
  frontend/src/data.js
Labels: FE, feat

#85 [FE] Fe/feat/issue detail
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/NewIssues/NewIssueInput.jsx
  frontend/src/components/common/Button/WhiteButtons.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/components/pages/NewIssuePage.jsx
  frontend/src/images/archive.svg
  frontend/src/styles/OpenLabel.jsx
  frontend/src/styles/StyledLayout .jsx
  frontend/src/util/fetchData.js
Labels: FE

#87 [FE] Fe/feat/issue detail 스타일링
  frontend/src/components/IssueDetail/IssueDatailHeader.jsx
  frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx
  frontend/src/components/IssueDetail/IssueDetailComments.jsx
  frontend/src/components/Labels/LabelCard.jsx
  frontend/src/components/Labels/LabelInput.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/components/pages/NewIssuePage.jsx
  frontend/src/images/alert-circle.svg
  frontend/src/styles/OpenLabel.jsx
  frontend/src/styles/StyledLayout.jsx
Labels: FE

#89 [FE] issue category list, modal view 완성
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx
  frontend/src/components/IssueDetail/IssueDetailHeader.jsx
  frontend/src/components/Labels/LabelCard.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/NewIssues/NewIssues.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/IssueCategory.jsx
  frontend/src/components/common/IssueCategory/Assignee.jsx
  frontend/src/components/common/IssueCategory/IssueCategory.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryList.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/components/common/IssueCategory/Label.jsx
  frontend/src/components/common/IssueCategory/MileStone.jsx
  frontend/src/components/common/IssueCategoryList.jsx
  frontend/src/components/common/LabelBadge.jsx
  frontend/src/components/pages/IssueDetailPage.jsx
  frontend/src/styles/StyledLayout.jsx
Labels: FE

#93 [FE] feat: 코멘트 이미지 업로드 기능 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/IssueDetail/IssueDetailCommentCard.jsx
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/MarkdownRenderer.jsx
  frontend/src/util/API.js
  frontend/src/util/fetchImage.js
  frontend/yarn.lock
Labels: FE

#91 [FE] new issue 구현
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/common/IssueCategory/Assignee.jsx
  frontend/src/components/common/IssueCategory/IssueCategory.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryList.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/components/common/IssueCategory/Label.jsx
  frontend/src/components/common/IssueCategory/MileStone.jsx
  frontend/src/data.js
  frontend/src/util/getCategoryText.js
Labels: FE, feat

#94 [FE] feat: 코멘트 인풋 및 이슈 인풋 상태관리
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/common/CommentInput.jsx
Labels: FE

#95 [FE] feat: 이미지 업로드 즉시 렌더링과 에러처리
  frontend/src/components/common/CommentInput.jsx
  frontend/src/components/common/MarkdownRenderer.jsx
Labels: FE

#96 [FE] issue filter modal 버그 해결
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/common/IssueCategory/Assignee.jsx
  frontend/src/components/common/IssueCategory/IssueCategory.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/components/common/IssueCategory/Label.jsx
  frontend/src/components/common/IssueCategory/Milestone.jsx
Labels: FE, fix

#97 [FE] issue POST 기능 완성
  frontend/src/RecoilStore/Atoms.jsx
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssueList.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/common/IssueCategory/IssueCategoryModal.jsx
  frontend/src/components/common/IssueCategory/Milestone.jsx
  frontend/src/util/API.js
Labels: FE

#98 [FE] feat: 이슈 페이지 스타일 수정
  frontend/src/components/Issues/IssueList/IssueCard.jsx
  frontend/src/components/Issues/IssueList/IssuesHeader.jsx
  frontend/src/components/NewIssues/NewIssueForm.jsx
  frontend/src/components/common/LabelBadge.jsx
Labels: FE

#99 [BE] issue filter기능
  BE/build.gradle
  BE/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issuetracker/issue/controller/IssueFilterController.java
  BE/src/main/java/com/codesquad/issuetracker/issue/domain/JpaIssueFilterRepository.java
  BE/src/main/java/com/codesquad/issuetracker/issue/dto/IssueFilter.java
  BE/src/main/java/com/codesquad/issuetracker/issue/infra/IssueFilterRepository.java
  BE/src/main/java/com/codesquad/issuetracker/issue/infra/IssueRepository.java
  BE/src/main/java/com/codesquad/issuetracker/issue/service/IssueFilterService.java
  BE/src/main/java/com/codesquad/issuetracker/issue/service/IssueService.java
Labels: BE, feat
